### ISSUE TITLE
Fails to Install on MacOS

### ISSUE THREAD

**Issue by rodydavis** [mishudark/fuchsiaos-sdk#1]
```
MightyMac:~ appleeducate$ source <(curl -s https://raw.githubusercontent.com/mishudark/fuchsiaos-sdk/master/fuchsia_sdk.sh)
MightyMac:~ appleeducate$ (23) Failed writing body
```

**Comment by mishudark** [comment]
Hi, thanks for the bug report, actually I've changed the install line to:

`curl -s https://raw.githubusercontent.com/mishudark/fuchsiaos-sdk/master/fuchsia_sdk.sh | bash`

if you can try this new way, could be great to close this issue

**Comment by rodydavis** [comment]
Worked perfectly thank you!
